import javax.swing.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import java.sql.*;
import java.awt.*;
import org.jfree.chart.axis.NumberAxis;
import java.text.DecimalFormat;
import org.jfree.chart.axis.NumberTickUnit;


/**
 *
 * @author MEGA GLOBAL GRUP
 */
public class owner_dashboard extends javax.swing.JFrame {

    private static final String DB_URL = "jdbc:mysql://localhost:3306/dinda_salon";
    private static final String DB_USER = "root";
    private static final String DB_PASS = "";
    /**
     * Creates new form Dashboard_Owner
     */
    public owner_dashboard() {
        initComponents();
        initChartPanel();
        loadTransactionData();
        setupButtonActions();
        setLocationRelativeTo(null);
    }
    
    

    private void initChartPanel() {
        // Set layout for jPanel1 which will contain our chart
        jPanel1.setLayout(new BorderLayout());
        jPanel1.setBackground(Color.WHITE);
        jPanel1.setPreferredSize(new Dimension(720, 260));
    }

  private void loadTransactionData() {
    try {
        // Connect to database
        Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASS);
        
        // Query to get monthly transaction totals
        String query = "SELECT DATE_FORMAT(tgl_transaksi, '%Y-%m') AS bulan, " +
                     "SUM(total_transaksi) AS total " +
                     "FROM transaksi " +
                     "GROUP BY DATE_FORMAT(tgl_transaksi, '%Y-%m') " +
                     "ORDER BY bulan DESC LIMIT 12";
        
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(query);
        
        // Prepare dataset for chart
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        while (rs.next()) {
            String month = rs.getString("bulan");
            double total = rs.getDouble("total");
            dataset.addValue(total, "Pendapatan", month);
        }
        
        // Create bar chart
        JFreeChart barChart = ChartFactory.createBarChart(
            "Statistik Transaksi 12 Bulan Terakhir", 
            "Bulan", 
            "Total Pendapatan (Rp)", 
            dataset
        );
        
        // Customize Y-axis
         NumberAxis rangeAxis = (NumberAxis) barChart.getCategoryPlot().getRangeAxis();
         rangeAxis.setRange(0, 1500000);
         rangeAxis.setTickUnit(new NumberTickUnit(300000)); // Menggunakan NumberTickUnit bukan NumberAxis.NumberAxis
         rangeAxis.setNumberFormatOverride(new DecimalFormat("#,###"));
        
        // Customize chart appearance
        barChart.setBackgroundPaint(Color.WHITE);
        
        // Create chart panel and add to jPanel1
        ChartPanel chartPanel = new ChartPanel(barChart);
        chartPanel.setPreferredSize(new Dimension(jPanel1.getWidth(), jPanel1.getHeight()));
        jPanel1.removeAll();
        jPanel1.add(chartPanel, BorderLayout.CENTER);
        jPanel1.revalidate();
        jPanel1.repaint();
        
        // Close connections
        rs.close();
        stmt.close();
        conn.close();
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, 
            "Error connecting to database: " + e.getMessage(), 
            "Database Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}
    
     private void setupButtonActions() {
        btnmembership.addActionListener(e -> {
            new owner_membership().setVisible(true);
            this.dispose();
        });
        
        btnkembali.addActionListener(e -> {
            // For back button - you can customize this
            System.exit(0); // Currently exits application
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmembership = new javax.swing.JButton();
        btnkembali = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmembership.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/Group 104.png"))); // NOI18N
        btnmembership.setContentAreaFilled(false);
        btnmembership.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/Group 104 (1).png"))); // NOI18N
        btnmembership.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/Group 104 (1).png"))); // NOI18N
        btnmembership.setBorderPainted(false);
        btnmembership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmembershipActionPerformed(evt);
            }
        });
        getContentPane().add(btnmembership, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, -1));

        btnkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/bck.png"))); // NOI18N
        btnkembali.setContentAreaFilled(false);
        btnkembali.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/bck1.png"))); // NOI18N
        btnkembali.setBorderPainted(false);
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 80, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 720, 260));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/Group 57.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/Group 57 (1).png"))); // NOI18N
        jButton2.setBorderPainted(false);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Group 90.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmembershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmembershipActionPerformed
        // TODO add your handling code here:
        owner_membership membershipForm = new owner_membership();
        membershipForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnmembershipActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnkembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(owner_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(owner_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(owner_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(owner_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new owner_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btnmembership;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
