<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BaseApp;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
=======
<<<<<<< HEAD
=======
>>>>>>> upstream/main
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896

package BaseApp;
import Base.*;
import java.io.File;
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> upstream/main
=======
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
>>>>>>> upstream/main
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
import javax.imageio.ImageIO;
=======
>>>>>>> upstream/main
=======
>>>>>>> upstream/main
=======
import javax.imageio.ImageIO;
=======
>>>>>>> upstream/main
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
import javax.swing.JTextPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
import javax.print.*;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.Copies;
import javax.print.attribute.standard.JobName;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;
/**
 *
 * @author ASUS
 */
public class TransaksiKasir extends javax.swing.JFrame {

    /**
     * Creates new form TreatmentKasir
     */
=======
public class TransaksiKasir extends javax.swing.JFrame {

>>>>>>> upstream/main
<<<<<<< HEAD
=======
public class TransaksiKasir extends javax.swing.JFrame {

>>>>>>> upstream/main
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
    public TransaksiKasir() {
        initComponents();
        setLocationRelativeTo(null);
        // Sembunyikan kolom "No." (kolom pertama di tampilan)
            TableColumnModel columnModel = tb_transaksi.getColumnModel();
            if (columnModel.getColumnCount() > 0) {
                columnModel.removeColumn(columnModel.getColumn(0)); // Kolom "No."
            }
        try {
            LoadData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data tidak berhasil tampil! Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnPrint = new javax.swing.JButton();
        btnLayanan = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnMember = new javax.swing.JButton();
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
        btnTransaksi = new javax.swing.JButton();
=======
>>>>>>> upstream/main
=======
>>>>>>> upstream/main
=======
        btnTransaksi = new javax.swing.JButton();
=======
>>>>>>> upstream/main
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        btnPembelian = new javax.swing.JButton();
        btnProduct = new javax.swing.JButton();
        btnTreatment = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_transaksi = new javax.swing.JTable();
        btnProduk = new javax.swing.JButton();
        labelTrans = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(936, 666));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrint.setContentAreaFilled(false);
        btnPrint.setBorderPainted(false);
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/print100.png"))); // NOI18N
        btnPrint.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/print50.png"))); // NOI18N
=======
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/btnprint.png"))); // NOI18N
        btnPrint.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bgprint.png"))); // NOI18N
>>>>>>> upstream/main
<<<<<<< HEAD
=======
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/btnprint.png"))); // NOI18N
        btnPrint.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bgprint.png"))); // NOI18N
>>>>>>> upstream/main
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        jPanel2.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 580, -1, -1));

        btnLayanan.setContentAreaFilled(false);
        btnLayanan.setBorderPainted(false);
        btnLayanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/Group 75.png"))); // NOI18N
        btnLayanan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/Group 75 (1).png"))); // NOI18N
=======
<<<<<<< HEAD
=======
>>>>>>> upstream/main
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        jPanel2.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 880, -1, -1));

        btnLayanan.setContentAreaFilled(false);
        btnLayanan.setBorderPainted(false);
        btnLayanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/btntrans.png"))); // NOI18N
        btnLayanan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bgtrans.png"))); // NOI18N
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> upstream/main
=======
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
>>>>>>> upstream/main
        btnLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayananActionPerformed(evt);
            }
        });
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        jPanel2.add(btnLayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 580, -1, -1));

        btnBack.setContentAreaFilled(false);
        btnBack.setBorderPainted(false);
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/back100.png"))); // NOI18N
        btnBack.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/back50.png"))); // NOI18N
=======
<<<<<<< HEAD
=======
>>>>>>> upstream/main
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        jPanel2.add(btnLayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 880, -1, -1));

        btnBack.setContentAreaFilled(false);
        btnBack.setBorderPainted(false);
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back.png"))); // NOI18N
        btnBack.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back1.png"))); // NOI18N
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> upstream/main
=======
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
>>>>>>> upstream/main
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 580, 73, 70));

        btnMember.setContentAreaFilled(false);
        btnMember.setBorderPainted(false);
        btnMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnMembership100.png"))); // NOI18N
        btnMember.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnMembership50.png"))); // NOI18N
=======
<<<<<<< HEAD
=======
>>>>>>> upstream/main
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 880, 90, 90));

        btnMember.setContentAreaFilled(false);
        btnMember.setBorderPainted(false);
        btnMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/btnmembership.png"))); // NOI18N
        btnMember.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bgmembership.png"))); // NOI18N
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> upstream/main
=======
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
>>>>>>> upstream/main
        btnMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemberActionPerformed(evt);
            }
        });
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        jPanel2.add(btnMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 290, 73, 70));

        btnTransaksi.setBorderPainted(false);
        btnTransaksi.setContentAreaFilled(false);
        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnTransaksi100.png"))); // NOI18N
        btnTransaksi.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnTransaksi50.png"))); // NOI18N
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });
        jPanel2.add(btnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 220, 73, 70));

        btnPembelian.setBorderPainted(false);
        btnPembelian.setContentAreaFilled(false);
        btnPembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnPembelian100.png"))); // NOI18N
        btnPembelian.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnPembelian50.png"))); // NOI18N
=======
<<<<<<< HEAD
=======
>>>>>>> upstream/main
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        jPanel2.add(btnMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 90, 90));

        btnPembelian.setBorderPainted(false);
        btnPembelian.setContentAreaFilled(false);
        btnPembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/btnpembelian.png"))); // NOI18N
        btnPembelian.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bgpembelian.png"))); // NOI18N
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> upstream/main
=======
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
>>>>>>> upstream/main
        btnPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembelianActionPerformed(evt);
            }
        });
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        jPanel2.add(btnPembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 150, 73, 70));

        btnProduct.setBorderPainted(false);
        btnProduct.setContentAreaFilled(false);
        btnProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnProduk100.png"))); // NOI18N
        btnProduct.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnProduk50.png"))); // NOI18N
=======
<<<<<<< HEAD
=======
>>>>>>> upstream/main
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        jPanel2.add(btnPembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, 90));

        btnProduct.setBorderPainted(false);
        btnProduct.setContentAreaFilled(false);
        btnProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/btnproduk.png"))); // NOI18N
        btnProduct.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bgproduk.png"))); // NOI18N
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> upstream/main
=======
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
>>>>>>> upstream/main
        btnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductActionPerformed(evt);
            }
        });
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        jPanel2.add(btnProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 80, 73, 70));

        btnTreatment.setBorderPainted(false);
        btnTreatment.setContentAreaFilled(false);
        btnTreatment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnTreatment100.png"))); // NOI18N
        btnTreatment.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnTreatment50.png"))); // NOI18N
=======
<<<<<<< HEAD
=======
>>>>>>> upstream/main
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        jPanel2.add(btnProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 90));

        btnTreatment.setBorderPainted(false);
        btnTreatment.setContentAreaFilled(false);
        btnTreatment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/btntreatment.png"))); // NOI18N
        btnTreatment.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bgtreatment.png"))); // NOI18N
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> upstream/main
=======
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
>>>>>>> upstream/main
        btnTreatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreatmentActionPerformed(evt);
            }
        });
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        jPanel2.add(btnTreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, 73, 70));

=======
        jPanel2.add(btnTreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 90));

        tb_transaksi.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
>>>>>>> upstream/main
<<<<<<< HEAD
=======
        jPanel2.add(btnTreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 90));

        tb_transaksi.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
>>>>>>> upstream/main
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        tb_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
                "idTrans", "Member", "Produk", "Layanan", "Tanggal", "Jumlah", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
=======
<<<<<<< HEAD
=======
>>>>>>> upstream/main
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
                "idDetail", "Member", "Produk", "Layanan", "Tanggal", "Jumlah", "Subtotal", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> upstream/main
=======
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
>>>>>>> upstream/main
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_transaksi);

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 740, 380));

        btnProduk.setContentAreaFilled(false);
        btnProduk.setBorderPainted(false);
        btnProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/Group 74.png"))); // NOI18N
        btnProduk.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/Group 74 (1).png"))); // NOI18N
=======
<<<<<<< HEAD
=======
>>>>>>> upstream/main
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 1130, 660));

        btnProduk.setContentAreaFilled(false);
        btnProduk.setBorderPainted(false);
        btnProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/buttransprod.png"))); // NOI18N
        btnProduk.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bgtransprod.png"))); // NOI18N
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> upstream/main
=======
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
>>>>>>> upstream/main
        btnProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdukActionPerformed(evt);
            }
        });
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        jPanel2.add(btnProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, -1, -1));

        labelTrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/designKasir/transaksi (1).png"))); // NOI18N
=======
        jPanel2.add(btnProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 880, -1, -1));

        labelTrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/transaksi.png"))); // NOI18N
>>>>>>> upstream/main
<<<<<<< HEAD
=======
        jPanel2.add(btnProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 880, -1, -1));

        labelTrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/transaksi.png"))); // NOI18N
>>>>>>> upstream/main
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        jPanel2.add(labelTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
=======
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE)
>>>>>>> upstream/main
<<<<<<< HEAD
=======
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE)
>>>>>>> upstream/main
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreatmentActionPerformed
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        TreatmentKasir abal = new TreatmentKasir();
        abal.setVisible(true);
        abal.pack();
        abal.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnTreatmentActionPerformed

    private void btnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductActionPerformed
        ProductKasir abal = new ProductKasir();
        abal.setVisible(true);
        abal.pack();
        abal.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnProductActionPerformed

    private void btnPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembelianActionPerformed
        PembelianKasir abal = new PembelianKasir();
        abal.setVisible(true);
        abal.pack();
        abal.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnPembelianActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        TransaksiKasir abal = new TransaksiKasir();
        abal.setVisible(true);
        abal.pack();
        abal.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemberActionPerformed
        MemberKasir abal = new MemberKasir();
        abal.setVisible(true);
        abal.pack();
        abal.setLocationRelativeTo(null);
        this.dispose();
=======
<<<<<<< HEAD
=======
>>>>>>> upstream/main
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        new TreatmentKasir().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTreatmentActionPerformed

    private void btnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductActionPerformed
        new ProdukKasir().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnProductActionPerformed

    private void btnPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembelianActionPerformed
        new PembelianKasir().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPembelianActionPerformed

    private void btnMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemberActionPerformed
        new MemberKasir().setVisible(true);
        dispose();
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> upstream/main
=======
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
>>>>>>> upstream/main
    }//GEN-LAST:event_btnMemberActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new DashboardKasir().setVisible(true);
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        this.dispose();
=======
        dispose();
>>>>>>> upstream/main
<<<<<<< HEAD
=======
        dispose();
>>>>>>> upstream/main
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdukActionPerformed
        new TransaksiProduk().setVisible(true);
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        this.dispose();
=======
        dispose();
>>>>>>> upstream/main
<<<<<<< HEAD
=======
        dispose();
>>>>>>> upstream/main
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
    }//GEN-LAST:event_btnProdukActionPerformed

    private void btnLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayananActionPerformed
        new TransaksiLayanan().setVisible(true);
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        this.dispose();
    }//GEN-LAST:event_btnLayananActionPerformed

    // Fungsi bantu untuk center text
    private String centerText(String text, int width) {
        if (text.length() >= width) return text;
        int leftPadding = (width - text.length()) / 2;
        return " ".repeat(leftPadding) + text;
    }
    
    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
            int selectedRow = tb_transaksi.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Pilih transaksi untuk dicetak!");
                return;
            }

            String url = "jdbc:mysql://localhost:3306/dinda_salon";
            String user = "root";
            String pw = "";

            try (Connection conn = DriverManager.getConnection(url, user, pw)) {
                

                String idTransaksi = tb_transaksi.getModel().getValueAt(selectedRow, 0).toString();
                String query = "SELECT * FROM vjual WHERE id_transaksi = ?";
                PreparedStatement stm = conn.prepareStatement(query);
                stm.setString(1, idTransaksi);
                ResultSet rs = stm.executeQuery();

                String namaKasir = "", namaMember = "", tanggal = "", total = "", bayar = "", kembali = "";
                List<String> produkList = new ArrayList<>();
                List<String> layananList = new ArrayList<>();

                while (rs.next()) {
                    namaMember = rs.getString("nama_member");
                    namaKasir = rs.getString("nama_user");
                    tanggal = rs.getString("tgl_transaksi");
                    total = rs.getString("total_transaksi");
                    bayar = rs.getString("bayar");
                    kembali = rs.getString("kembali");

                    String namaLayanan = rs.getString("nama_layanan");
                    String namaProduk = rs.getString("nama_produk");
                    int jumlah = rs.getInt("jumlah_jual");
                    int subtotal = rs.getInt("subtotal");

                    String idLayanan = rs.getString("id_layanan");
                    String kdProduk = rs.getString("kd_produk");

                    if (kdProduk != null && !"P000000".equals(kdProduk)) {
                        String produkLine = String.format("%-20s %10s", namaProduk + " x" + jumlah, String.format("Rp%,d", subtotal));
                        produkList.add(produkLine);
                    } else if (idLayanan != null && !"1".equals(idLayanan)) {
                        String layananLine = String.format("%-20s %10s", namaLayanan + " x" + jumlah, String.format("Rp%,d", subtotal));
                        layananList.add(layananLine);
                    }
                }

                int lineWidth = 32;
                StringBuilder receipt = new StringBuilder();
                receipt.append("-".repeat(lineWidth)).append("\n");
                receipt.append(String.format("No Transaksi : %s\n", idTransaksi));
                receipt.append(String.format("Tanggal      : %s\n", tanggal));
                receipt.append(String.format("Pelanggan    : %s\n", namaMember));
                receipt.append(String.format("Kasir        : %s\n", namaKasir));
                receipt.append("-".repeat(lineWidth)).append("\n");

                if (!produkList.isEmpty()) {
                    receipt.append(centerText("PRODUK:", lineWidth)).append("\n");
                    for (String item : produkList) receipt.append(item).append("\n");
                    receipt.append("-".repeat(lineWidth)).append("\n");
                }

                if (!layananList.isEmpty()) {
                    receipt.append(centerText("LAYANAN:", lineWidth)).append("\n");
                    for (String item : layananList) receipt.append(item).append("\n");
                    receipt.append("-".repeat(lineWidth)).append("\n");
                }

                String[] opsi = {"Cetak ke Printer", "Pratinjau Struk"};
                int pilihan = JOptionPane.showOptionDialog(this, "Pilih metode:", "Cetak atau Pratinjau",
                        JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opsi, opsi[0]);

                if (pilihan == 0) {
                    // ESC/POS commands
                    byte[] initPrinter = {0x1B, 0x40};
                    byte[] doubleFont = {0x1B, 0x21, 0x30};
                    byte[] normalFont = {0x1B, 0x21, 0x00};
                    byte[] partialCut = {0x1D, 0x56, 0x42, 0x00};

                    ByteArrayOutputStream finalBytes = new ByteArrayOutputStream();
                    finalBytes.write(initPrinter);
                    finalBytes.write(doubleFont);
                    finalBytes.write(("  DINDA SALON").getBytes(StandardCharsets.UTF_8));
                    finalBytes.write("\n".getBytes());
                    finalBytes.write(normalFont);
                    finalBytes.write(centerText("Jl. Gajah Mada - Jember", lineWidth).getBytes(StandardCharsets.UTF_8));
                    finalBytes.write("\n".getBytes());
                    finalBytes.write(centerText("Telp: 0812 3456 7890", lineWidth).getBytes(StandardCharsets.UTF_8));
                    finalBytes.write("\n".getBytes());
                    finalBytes.write("-".repeat(lineWidth).getBytes(StandardCharsets.UTF_8));
                    finalBytes.write("\n".getBytes());

                    finalBytes.write(receipt.toString().getBytes(StandardCharsets.UTF_8));

                    // Besarkan bagian total akhir
                    finalBytes.write(String.format("%-20s %10s\n", "TOTAL", String.format("Rp%,d", Integer.parseInt(total))).getBytes(StandardCharsets.UTF_8));
                    finalBytes.write(String.format("%-20s %10s\n", "BAYAR", String.format("Rp%,d", Integer.parseInt(bayar))).getBytes(StandardCharsets.UTF_8));
                    finalBytes.write(String.format("%-20s %10s\n", "KEMBALI", String.format("Rp%,d", Integer.parseInt(kembali))).getBytes(StandardCharsets.UTF_8));
                    finalBytes.write(normalFont);

                    finalBytes.write("-".repeat(lineWidth).getBytes(StandardCharsets.UTF_8));
                    finalBytes.write("\n".getBytes());
                    finalBytes.write(centerText("Terima kasih atas kunjungan Anda", lineWidth).getBytes(StandardCharsets.UTF_8));
                    finalBytes.write("\n".getBytes());
                    finalBytes.write(centerText("https://encr.pw/dinda-Salon", lineWidth).getBytes(StandardCharsets.UTF_8));
                    finalBytes.write("\n".getBytes());
                    finalBytes.write("-".repeat(lineWidth).getBytes(StandardCharsets.UTF_8));
                    finalBytes.write("\n".getBytes());

                    for (int i = 0; i < 5; i++) finalBytes.write(0x0A);
                    finalBytes.write(partialCut);

                    PrintService selectedPrintService = null;
                    PrintService[] printServices = PrintServiceLookup.lookupPrintServices(null, null);
                    for (PrintService service : printServices) {
                        if (service.isDocFlavorSupported(DocFlavor.BYTE_ARRAY.AUTOSENSE)) {
                            selectedPrintService = service;
                            break;
                        }
                    }

                    if (selectedPrintService != null) {
                        DocPrintJob job = selectedPrintService.createPrintJob();
                        Doc doc = new SimpleDoc(finalBytes.toByteArray(), DocFlavor.BYTE_ARRAY.AUTOSENSE, null);
                        PrintRequestAttributeSet aset = new HashPrintRequestAttributeSet();
                        aset.add(new Copies(1));
                        aset.add(new JobName("Struk Dinda Salon", null));
                        job.print(doc, aset);
                        JOptionPane.showMessageDialog(this, "Struk berhasil dicetak.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Printer tidak ditemukan atau tidak mendukung data mentah.");
                    }

                } else if (pilihan == 1) {
                    JTextArea textArea = new JTextArea();
                    textArea.setFont(new Font("Monospaced", Font.PLAIN, 17));

                    StringBuilder preview = new StringBuilder();
                    preview.append("  DINDA SALON\n");
                    preview.append(centerText("Jl. Gajah Mada - Jember", lineWidth)).append("\n");
                    preview.append(centerText("Telp: 0812 3456 7890", lineWidth)).append("\n");
                    preview.append("-".repeat(lineWidth)).append("\n");
                    preview.append(receipt);
                    preview.append(String.format("%-20s %10s\n", "TOTAL", String.format("Rp%,d", Integer.parseInt(total))));
                    preview.append(String.format("%-20s %10s\n", "BAYAR", String.format("Rp%,d", Integer.parseInt(bayar))));
                    preview.append(String.format("%-20s %10s\n", "KEMBALI", String.format("Rp%,d", Integer.parseInt(kembali))));
                    preview.append("-".repeat(lineWidth)).append("\n");
                    preview.append(centerText("Terima kasih atas kunjungan Anda", lineWidth)).append("\n");
                    preview.append(centerText("https://encr.pw/dinda-Salon", lineWidth)).append("\n");
                    preview.append("-".repeat(lineWidth)).append("\n");

                    textArea.setText(preview.toString());
                    textArea.setEditable(false);

                    JPanel panel = new JPanel(new BorderLayout());
                    JLabel titleLabel = new JLabel("DINDA SALON", SwingConstants.CENTER);
                    titleLabel.setFont(new Font("Serif", Font.BOLD, 22));

                    panel.add(titleLabel, BorderLayout.NORTH);
                    panel.add(new JScrollPane(textArea), BorderLayout.CENTER);
                    panel.setPreferredSize(new Dimension(400, 600));

                    JOptionPane.showMessageDialog(this, panel, "Pratinjau Struk", JOptionPane.INFORMATION_MESSAGE);
                }

            } catch (SQLException | IOException | PrintException ex) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage());
                ex.printStackTrace();
            }
    }//GEN-LAST:event_btnPrintActionPerformed
   
    /**
    * Convert BufferedImage ke format ESC/POS (bit image) agar bisa dicetak di printer thermal.
    * Ini sederhana, bisa dimodifikasi sesuai printer dan resolusi.
    */
   // Konversi gambar ke format ESC/POS
    private byte[] convertImageToESCPosBytes(BufferedImage image) throws IOException {
        int width = image.getWidth();
        int height = image.getHeight();
        ByteArrayOutputStream baos = new ByteArrayOutputStream();

        for (int y = 0; y < height; y += 24) {
            baos.write(new byte[]{0x1B, 0x2A, 33, (byte)(width % 256), (byte)(width / 256)});
            for (int x = 0; x < width; x++) {
                for (int k = 0; k < 3; k++) {
                    byte slice = 0;
                    for (int b = 0; b < 8; b++) {
                        int yPos = y + (k * 8) + b;
                        if (yPos >= height) continue;
                        int color = image.getRGB(x, yPos);
                        int r = (color >> 16) & 0xFF;
                        int g = (color >> 8) & 0xFF;
                        int bVal = color & 0xFF;
                        int luminance = (r + g + bVal) / 3;
                        if (luminance < 128) {
                            slice |= (1 << (7 - b));
                        }
                    }
                    baos.write(slice);
                }
            }
            baos.write(0x0A);
        }
        return baos.toByteArray();
    }
    
=======
<<<<<<< HEAD
=======
>>>>>>> upstream/main
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        dispose();
    }//GEN-LAST:event_btnLayananActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
           String username = SessionLogin.getUsername();
    if (username == null || username.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Username tidak ditemukan. Silakan login kembali!");
        return;
    }
        
        int selectedRow = tb_transaksi.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih transaksi untuk dicetak!");
            return;
        }

        String idDetail = tb_transaksi.getModel().getValueAt(selectedRow, 0).toString();
        String url = "jdbc:mysql://localhost:3306/dinda_salon";
        String user = "root";
        String pw = "";

        try {
            Connection conn = DriverManager.getConnection(url, user, pw);

            // Ambil id_transaksi dari id_detail
            String getIdTransQuery = "SELECT id_transaksi FROM vjual WHERE id_detail = ?";
            java.sql.PreparedStatement getIdTransStm = conn.prepareStatement(getIdTransQuery);
            getIdTransStm.setString(1, idDetail);
            java.sql.ResultSet rsTrans = getIdTransStm.executeQuery();

            if (!rsTrans.next()) {
                JOptionPane.showMessageDialog(this, "Data transaksi tidak ditemukan.");
                return;
            }

            String idTransaksi = rsTrans.getString("id_transaksi");

            // Ambil semua detail untuk transaksi tersebut
            String query = "SELECT * FROM vjual WHERE id_transaksi = ?";
            java.sql.PreparedStatement stm = conn.prepareStatement(query);
            stm.setString(1, idTransaksi);
            java.sql.ResultSet rs = stm.executeQuery();

            String namaKasir = "", namaMember = "", tanggal = "", total = "", bayar = "", kembali = "";
            List<String> produkList = new ArrayList<>();
            List<String> layananList = new ArrayList<>();

            while (rs.next()) {
                namaMember = rs.getString("nama_member");
                namaKasir = rs.getString("nama_user");
                tanggal = rs.getString("tgl_transaksi");
                total = rs.getString("total_transaksi");
                bayar = rs.getString("bayar");
                kembali = rs.getString("kembali");

                String namaLayanan = rs.getString("nama_layanan");
                int jumlah = rs.getInt("jumlah_jual");
                int subtotal = rs.getInt("subtotal");

                String idLayanan = rs.getString("id_layanan");
                String kdProduk = rs.getString("kd_produk");

                if (!"P000000".equals(kdProduk)) {
                    // Ini produk valid
                    produkList.add(String.format("%s x%d - Rp%,d", namaLayanan, jumlah, subtotal));
                } else if (!"1".equals(idLayanan)) {
                    // Ini layanan valid
                    layananList.add(String.format("%s x%d - Rp%,d", namaLayanan, jumlah, subtotal));
                }
            }


            // Path ke logo (ubah sesuai lokasi Anda)
            String logoPath = new File("src/design_/Logo1.png").toURI().toURL().toString();

            // HTML Template
            StringBuilder html = new StringBuilder();
            html.append("<html><body style='font-family:monospace;'>");
            html.append("<div style='text-align:center;'>");
            html.append("<img src='").append(logoPath).append("' width='100'/><br/>");
            html.append("<b style='font-size:14pt;'>DINDA SALON</b><br/>");
            html.append("Jl. Gajah Mada - Garut<br/>");
            html.append("Telp: 0812 3456 7890<br/>");
            html.append("</div><hr/>");
            html.append("<b>No Transaksi :</b> ").append(idTransaksi).append("<br/>");
            html.append("<b>Tanggal      :</b> ").append(tanggal).append("<br/>");
            html.append("<b>Pelanggan    :</b> ").append(namaMember).append("<br/>");
            html.append("<b>Kasir        :</b> ").append(namaKasir).append("<br/>");
            html.append("<hr/>");

            // Jika ada produk, tampilkan bagian Produk
            if (!produkList.isEmpty()) {
                html.append("<b>Produk:</b><br/>");
                for (String item : produkList) {
                    html.append(item).append("<br/>");
                }
            }

            // Jika ada layanan, tampilkan bagian Layanan
            if (!layananList.isEmpty()) {
                html.append("<b>Layanan:</b><br/>");
                for (String item : layananList) {
                    html.append(item).append("<br/>");
                }
            }

            html.append("<hr/>");
            html.append(String.format("<b>Total    :</b> Rp%,d<br/>", Integer.parseInt(total)));
            html.append(String.format("<b>Bayar    :</b> Rp%,d<br/>", Integer.parseInt(bayar)));
            html.append(String.format("<b>Kembali  :</b> Rp%,d<br/>", Integer.parseInt(kembali)));
            html.append("<hr/>");
            html.append("<center>Terima kasih atas kunjungan Anda<br/>www.dindasalon.com</center>");
            html.append("</body></html>");


            // Tampilkan & cetak HTML struk
            JTextPane pane = new JTextPane();
            pane.setContentType("text/html");
            pane.setText(html.toString());
            pane.setEditable(false);
            pane.print();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mencetak: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPrintActionPerformed
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> upstream/main
=======
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
>>>>>>> upstream/main
    public void LoadData() throws java.sql.SQLException {
        String url = "jdbc:mysql://localhost:3306/dinda_salon";
        String user = "root";
        String pw = "";
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        String Query = "SELECT \n" +
                        "    id_transaksi,\n" +
                        "    MAX(nama_member) AS nama_member,\n" +
                        "    GROUP_CONCAT(nama_produk SEPARATOR ', ') AS nama_produk,\n" +
                        "    GROUP_CONCAT(nama_layanan SEPARATOR ', ') AS nama_layanan,\n" +
                        "    MAX(tgl_transaksi) AS tgl_transaksi,\n" +
                        "    SUM(jumlah_jual) AS jumlah_jual,\n" +
                        "    SUM(subtotal) AS subtotal,\n" +
                        "    MAX(total_transaksi) AS total_transaksi\n" +
                        "FROM vJual\n" +
                        "GROUP BY id_transaksi\n" +
                        "ORDER BY tgl_transaksi DESC;";
=======
        String Query = "SELECT id_detail, nama_member, nama_layanan, nama_produk, tgl_transaksi, jumlah_jual, subtotal, total_transaksi FROM vJual ORDER BY tgl_transaksi DESC";
        
>>>>>>> upstream/main
<<<<<<< HEAD
=======
        String Query = "SELECT id_detail, nama_member, nama_layanan, nama_produk, tgl_transaksi, jumlah_jual, subtotal, total_transaksi FROM vJual ORDER BY tgl_transaksi DESC";
        
>>>>>>> upstream/main
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        try {
            Connection connect = java.sql.DriverManager.getConnection(url, user, pw);
            java.sql.Statement stm = connect.createStatement();
            java.sql.ResultSet rs = stm.executeQuery(Query);
            
            DefaultTableModel model = (DefaultTableModel) tb_transaksi.getModel();
            model.setRowCount(0);
            
            while (rs.next()) {                
                Object[] row = {
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
                rs.getString("id_transaksi"),
                rs.getString("nama_member"),
                rs.getString("nama_produk"),
                rs.getString("nama_layanan"),
                rs.getString("tgl_transaksi"),
                rs.getString("jumlah_jual"),
=======
<<<<<<< HEAD
=======
>>>>>>> upstream/main
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
                rs.getString("id_detail"),
                rs.getString("nama_member"),
                rs.getString("nama_layanan"),
                rs.getString("nama_produk"),
                rs.getString("tgl_transaksi"),
                rs.getString("jumlah_jual"),
                rs.getString("subtotal"),
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> upstream/main
=======
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
>>>>>>> upstream/main
                rs.getString("total_transaksi")
                };
                model.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data tidak bisa tampil! Error: " + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
        System.setProperty("sun.java2d.uiScale", "1");
>>>>>>> upstream/main
=======
        System.setProperty("sun.java2d.uiScale", "1");
>>>>>>> upstream/main
=======
=======
        System.setProperty("sun.java2d.uiScale", "1");
>>>>>>> upstream/main
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
=======
>>>>>>> upstream/main
<<<<<<< HEAD
=======
>>>>>>> upstream/main
=======
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLayanan;
    private javax.swing.JButton btnMember;
    private javax.swing.JButton btnPembelian;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnProduk;
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    private javax.swing.JButton btnTransaksi;
=======
>>>>>>> upstream/main
=======
>>>>>>> upstream/main
=======
    private javax.swing.JButton btnTransaksi;
=======
>>>>>>> upstream/main
>>>>>>> 49a97e0045e2a45eda10793666a89f011bea1896
    private javax.swing.JButton btnTreatment;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTrans;
    private javax.swing.JTable tb_transaksi;
    // End of variables declaration//GEN-END:variables
}
